# -*- coding: utf-8 -*-
"""no_name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEUD26LdLMwzH0KFLTDzgj4M0uV66aB0
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from scipy.fft import dst, idst
from IPython.display import HTML, display
# Jorge Acebes y Andrés López
# Se observa la propagación de la onda hacia la izquierda y su posterior ensanche con el paso del tiempo

# Parámetros físicos
m = 9.109e-31
hbar = 1.0546e-34
L = 1e-8
x0 = L / 2.0
sigma = 1e-10
kappa = 5e10
N = 1000

# 1. Malla espacial (solo nodos interiores)
x = np.linspace(0, L, N + 1)
x_int = x[1:-1]

# Estado inicial
gauss_env = np.exp(-0.5 * ((x_int - x0) / sigma)**2)
psi_r_0 = gauss_env * np.cos(kappa * x_int)
psi_i_0 = gauss_env * np.sin(kappa * x_int)

# Transformada espectral (DST de Tipo 1)
alpha = dst(psi_r_0, type=1)
eta = dst(psi_i_0, type=1)

# Relación de dispersión
k_vec = np.arange(1, N)
omega = (np.pi**2 * hbar * k_vec**2) / (2 * m * L**2)

# 3. Animación
dt = 1e-18
fig, ax = plt.subplots(figsize=(8, 4))
line, = ax.plot(x, np.zeros_like(x), color='navy', lw=1.5)

ax.set_xlim(0, L)
ax.set_ylim(-1.5, 1.5)
ax.set_xlabel(r'$x$ (m)')
ax.set_ylabel(r'$\Re[\psi(x,t)]$')
title = ax.set_title('')
ax.grid(True, alpha=0.3)

def update(frame):
    t = frame * dt
    coef_t = alpha * np.cos(omega * t) - eta * np.sin(omega * t)
    psi_r = np.zeros(N + 1)
    psi_r[1:-1] = idst(coef_t, type=1)
    line.set_ydata(psi_r)
    title.set_text(f'$t = {t:.2e}$ s')
    return line, title

ani = FuncAnimation(fig, update, frames=300, interval=40, blit=True)

plt.close(fig) # Evita que se imprima un frame estático duplicado
display(HTML(ani.to_jshtml()))