# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wb4dj36kMPAJr9J52UHE4-EqyRcwfIP-
"""

# Colaboradores: Jorge Acebes Hernández y Andrés López Serna

import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import solve_banded
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# 1. Parámetros físicos
m = 9.109e-31        # Masa del electrón (kg)
L = 1e-8             # Longitud de la caja (m)
hbar = 1.0546e-34    # Constante de Planck reducida (J s)
N = 1000             # Número de puntos espaciales
a = L / N            # Paso espacial (m)
h_t = 1e-18          # Paso temporal (s)

x0 = L / 2
sigma = 1e-10
kappa = 5e10

# 2. Malla espacial (excluimos las fronteras para forzar psi=0 implícitamente)
x = np.linspace(a, L - a, N - 1)

# Condición inicial (debe ser estritamente compleja debido a kappa)
psi = np.exp(-(x - x0)**2 / (2 * sigma**2)) * np.exp(1j * kappa * x)
# Normalización del vector de estado
psi = psi / np.sqrt(np.sum(np.abs(psi)**2) * a)

# 3. Constantes de Crank-Nicolson
alpha = (hbar * h_t) / (4 * m * a**2)
a1 = 1 + 2j * alpha
a2 = -1j * alpha
b1 = 1 - 2j * alpha
b2 = 1j * alpha

# Matriz A formateada para solve_banded (3 bandas, N-1 columnas)
A_band = np.zeros((3, N - 1), dtype=np.complex128)
A_band[0, 1:] = a2  # Diagonal superior
A_band[1, :] = a1   # Diagonal principal
A_band[2, :-1] = a2 # Diagonal inferior

# 4. Configuración del espacio de representación
fig, ax = plt.subplots(figsize=(10, 5))
ax.set_xlim(0, L)

psi_max = np.max(np.real(psi))
ax.set_ylim(-psi_max * 1.5, psi_max * 1.5)

ax.set_xlabel('Posición $x$ (m)')
ax.set_ylabel(r'$Re(\psi)$')
ax.set_title('Evolución temporal del paquete de ondas ($Re(\psi)$)')
ax.grid(True, linestyle='--', alpha=0.5)

line, = ax.plot(x, np.real(psi), color='blue')
plt.close() # Previene el renderizado del frame inicial estático en Colab

# 5. Evolución temporal optimizada
def update(frame):
    global psi
    # Aceleramos la visualización calculando 20 pasos de integración por cada fotograma
    for _ in range(20):
        # Operación matricial v = b1 * psi_0 + b2 (psi_+1 + psi_-1)
        v = np.zeros_like(psi)
        v[0] = b1 * psi[0] + b2 * psi[1]
        v[-1] = b1 * psi[-1] + b2 * psi[-2]
        v[1:-1] = b1 * psi[1:-1] + b2 * (psi[2:] + psi[:-2])

        # Resolución lineal A * psi_new = v con solve_banded
        psi = solve_banded((1, 1), A_band, v)

    line.set_ydata(np.real(psi))
    return line,

# Construcción de la animación (100 frames = 2000 pasos de tiempo)
anim = FuncAnimation(fig, update, frames=200, interval=50, blit=True)

# Renderizado interactivo en celdas de Jupyter / Colab
HTML(anim.to_jshtml())

"""El paquete de ondas, inicialmente centrado en $x=L/2$, avanza hacia $x=L$ 
portando un momento lineal positivo caracterizado por $p=\hbar\kappa$. 
A medida que se desplaza en el tiempo, la función se ensancha espacialmente
 debido a que, en mecánica cuántica, la relación de dispersión para una partícula 
 libre es cuadrática ($E = p^2/2m$), causando que las distintas frecuencias que 
 componen el pulso gaussiano viajen a velocidades de fase distintas. Al llegar a 
 la barrera de potencial infinita, el paquete de ondas se refleja, invirtiendo su 
 momento. La superposición de la parte de la onda incidente con la que acaba de 
 reflejarse da lugar a una interferencia de ambas ondas de forma transitoria.

"""

